# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN="48d50e64-fae6-45fd-a7ee-75a224df401e"

notifications:
  email:
    recipients:
      -sekator778@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
